#!/usr/bin/env python3
"""
Python AI Documentation Generator
Automatically generates and updates Python project documentation
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from typing import Dict, List, Any
import openai
from dotenv import load_dotenv

# Load environment variables
load_dotenv()
openai.api_type = "azure"
openai.api_key = os.getenv("AZURE_OPENAI_API_KEY")
openai.api_version = os.getenv("AZURE_OPENAI_API_VERSION")
openai.azure_endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")


class PythonDocumentationGenerator:
    def __init__(self):
        self.output_dir = Path.cwd() / "docs"
        self.temp_dir = Path.cwd() / "temp" / "ai-outputs"
        self.project_config = self.load_project_config()
        self.deployment_name = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME", "gpt-4.1")
        self.temperature = float(os.getenv("AI_TEMPERATURE", "0.3"))
        self.max_tokens = int(os.getenv("AI_MAX_TOKENS", "2000"))
        self.output_dir.mkdir(exist_ok=True)
        self.temp_dir.mkdir(parents=True, exist_ok=True)

    def load_project_config(self) -> Dict[str, Any]:
        """Load project configuration from .copilotflow.json"""
        try:
            config_path = Path.cwd() / ".copilotflow.json"
            if config_path.exists():
                with open(config_path, "r", encoding="utf-8") as f:
                    return json.load(f)
        except Exception as e:
            print(f"⚠️ Could not load project config: {e}")

        return {"primaryLanguage": "python", "projectType": "custom"}

    def generate_docs(self):
        """Generate comprehensive Python documentation"""
        print("📝 Starting Python AI Documentation Generation...\n")

        tasks = [
            ("API Documentation", self.generate_api_docs),
            ("Module Documentation", self.generate_module_docs),
            ("Installation Guide", self.generate_installation_guide),
            ("User Guide", self.generate_user_guide),
            ("Developer Guide", self.generate_developer_guide),
            ("Contributing Guide", self.generate_contributing_guide),
        ]

        results = {}

        for task_name, task_func in tasks:
            print(f"📋 Generating: {task_name}")
            try:
                results[task_name] = task_func()
                print(f"✅ Completed: {task_name}\n")
            except Exception as e:
                print(f"❌ Failed: {task_name} - {e}\n")
                results[task_name] = {"error": str(e)}

        self.update_main_readme()
        self.generate_index(results)

        print("🎉 Python documentation generation completed!")

    def generate_api_docs(self) -> Dict[str, Any]:
        """Generate API documentation for Python endpoints"""
        python_files = self.get_python_files()
        api_endpoints = self.extract_api_endpoints(python_files)

        if not api_endpoints:
            return {"message": "No API endpoints found"}

        prompt = f"""
        Generate comprehensive API documentation for the following Python endpoints:
        
        {self.format_endpoints_for_prompt(api_endpoints)}
        
        Please provide:
        1. Clear endpoint descriptions
        2. Request/response schemas (using Pydantic models if available)
        3. Authentication requirements
        4. Example requests and responses
        5. Error codes and messages
        6. Python client examples
        
        Format as Markdown with proper Python code blocks.
        """

        response = openai.chat.completions.create(
            model=self.deployment_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=self.temperature,
            max_tokens=self.max_tokens,
        )

        api_docs = response.choices[0].message.content

        # Write to file
        api_file = self.output_dir / "API.md"
        with open(api_file, "w", encoding="utf-8") as f:
            f.write(f"# API Documentation\n\n{api_docs}\n\n---\n*Generated by CopilotFlow AI*")

        return {"endpoints_documented": len(api_endpoints), "file_path": "docs/API.md"}

    def generate_module_docs(self) -> Dict[str, Any]:
        """Generate module documentation"""
        modules = self.extract_python_modules()

        prompt = f"""
        Generate comprehensive Python module documentation:
        
        Project: {self.project_config.get('projectName', 'Unknown')}
        Modules: {json.dumps(modules, indent=2)}
        
        Please provide:
        1. Module overviews with clear descriptions
        2. Class documentation with attributes and methods
        3. Function documentation with parameters and return values
        4. Usage examples for each module
        5. Import instructions
        6. Dependencies and requirements
        
        Format as Markdown with Python code examples.
        """

        response = openai.chat.completions.create(
            model=self.deployment_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=self.temperature,
            max_tokens=self.max_tokens,
        )

        module_docs = response.choices[0].message.content

        # Write to file
        modules_file = self.output_dir / "MODULES.md"
        with open(modules_file, "w", encoding="utf-8") as f:
            f.write(f"# Python Module Documentation\n\n{module_docs}\n\n---\n*Generated by CopilotFlow AI*")

        return {"modules_documented": len(modules), "file_path": "docs/MODULES.md"}

    def generate_installation_guide(self) -> Dict[str, Any]:
        """Generate installation guide"""
        requirements = self.get_requirements()
        setup_info = self.get_setup_info()

        prompt = f"""
        Generate a comprehensive installation guide for this Python project:
        
        Project: {self.project_config.get('projectName', 'Unknown')}
        Requirements: {requirements}
        Setup Info: {setup_info}
        
        Please provide:
        1. System requirements
        2. Python version requirements
        3. Virtual environment setup instructions
        4. Package installation steps
        5. Configuration instructions
        6. Verification steps
        7. Troubleshooting common issues
        
        Format as Markdown with clear step-by-step instructions.
        """

        response = openai.chat.completions.create(
            model=self.deployment_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=self.temperature,
            max_tokens=self.max_tokens,
        )

        install_guide = response.choices[0].message.content

        # Write to file
        install_file = self.output_dir / "INSTALLATION.md"
        with open(install_file, "w", encoding="utf-8") as f:
            f.write(f"# Installation Guide\n\n{install_guide}\n\n---\n*Generated by CopilotFlow AI*")

        return {"file_path": "docs/INSTALLATION.md"}

    def generate_user_guide(self) -> Dict[str, Any]:
        """Generate user guide"""
        prompt = f"""
        Generate a comprehensive user guide for this Python project:
        Project: {self.project_config.get('projectName', 'Unknown')}
        Please provide:
        1. Overview and main features
        2. Getting started instructions
        3. Example usage
        4. Common workflows
        5. Troubleshooting tips
        Format as Markdown.
        """

        response = openai.chat.completions.create(
            model=self.deployment_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=self.temperature,
            max_tokens=self.max_tokens,
        )

        user_guide = response.choices[0].message.content

        # Write to file
        user_file = self.output_dir / "USER_GUIDE.md"
        with open(user_file, "w", encoding="utf-8") as f:
            f.write(f"# User Guide\n\n{user_guide}\n\n---\n*Generated by CopilotFlow AI*")

        return {"file_path": "docs/USER_GUIDE.md"}

    def generate_developer_guide(self) -> Dict[str, Any]:
        """Generate developer guide"""
        prompt = f"""
        Generate a comprehensive developer guide for this Python project:
        Project: {self.project_config.get('projectName', 'Unknown')}
        Please provide:
        1. Project architecture overview
        2. Development setup instructions
        3. Coding standards and best practices
        4. Testing and validation
        5. Contribution guidelines
        Format as Markdown.
        """

        response = openai.chat.completions.create(
            model=self.deployment_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=self.temperature,
            max_tokens=self.max_tokens,
        )

        dev_guide = response.choices[0].message.content

        # Write to file
        dev_file = self.output_dir / "DEVELOPER_GUIDE.md"
        with open(dev_file, "w", encoding="utf-8") as f:
            f.write(f"# Developer Guide\n\n{dev_guide}\n\n---\n*Generated by CopilotFlow AI*")

        return {"file_path": "docs/DEVELOPER_GUIDE.md"}

    def generate_contributing_guide(self) -> Dict[str, Any]:
        """Generate contributing guide"""
        prompt = f"""
        Generate a comprehensive contributing guide for this Python project:
        Project: {self.project_config.get('projectName', 'Unknown')}
        Please provide:
        1. How to contribute
        2. Code review process
        3. Issue and PR guidelines
        4. Community standards
        Format as Markdown.
        """

        response = openai.chat.completions.create(
            model=self.deployment_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=self.temperature,
            max_tokens=self.max_tokens,
        )

        contrib_guide = response.choices[0].message.content

        # Write to file
        contrib_file = self.output_dir / "CONTRIBUTING.md"
        with open(contrib_file, "w", encoding="utf-8") as f:
            f.write(f"# Contributing Guide\n\n{contrib_guide}\n\n---\n*Generated by CopilotFlow AI*")

        return {"file_path": "docs/CONTRIBUTING.md"}

    def get_python_files(self) -> List[str]:
        """Get all Python files in the project"""
        python_files = []
        for file_path in Path.cwd().rglob("*.py"):
            if "venv" not in str(file_path) and "__pycache__" not in str(file_path):
                python_files.append(str(file_path))
        return python_files[:20]  # Limit to first 20 files

    def extract_api_endpoints(self, files: List[str]) -> List[Dict[str, Any]]:
        """Extract API endpoints from Python files"""
        endpoints = []

        for file_path in files:
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()

                # Look for FastAPI, Flask, or Django patterns
                patterns = [
                    r'@app\\.(get|post|put|delete|patch)\\(["\']([^"\']+)["\']',
                    r'@router\\.(get|post|put|delete|patch)\\(["\']([^"\']+)["\']',
                    r"def\\s+(\\w+)\\([^)]*request[^)]*\\)",
                ]

                import re

                for pattern in patterns:
                    matches = re.finditer(pattern, content, re.IGNORECASE)
                    for match in matches:
                        endpoints.append(
                            {
                                "file": file_path,
                                "method": (
                                    match.group(1).upper()
                                    if len(match.groups()) > 1
                                    else "GET"
                                ),
                                "path": (
                                    match.group(2)
                                    if len(match.groups()) > 1
                                    else match.group(1)
                                ),
                                "code": content[
                                    max(0, match.start() - 100) : match.end() + 200
                                ],
                            }
                        )
            except Exception:
                continue

        return endpoints

    def extract_python_modules(self) -> List[Dict[str, Any]]:
        """Extract Python modules information"""
        modules = []

        for file_path in self.get_python_files():
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read()

                module_name = Path(file_path).stem

                # Extract classes and functions
                import ast

                tree = ast.parse(content)

                classes = [
                    node.name
                    for node in ast.walk(tree)
                    if isinstance(node, ast.ClassDef)
                ]
                functions = [
                    node.name
                    for node in ast.walk(tree)
                    if isinstance(node, ast.FunctionDef)
                ]

                # Extract docstring
                docstring = ast.get_docstring(tree) or ""

                modules.append(
                    {
                        "name": module_name,
                        "file": file_path,
                        "classes": classes,
                        "functions": functions,
                        "docstring": docstring,
                    }
                )
            except Exception:
                continue

        return modules

    def get_requirements(self) -> str:
        """Get requirements.txt content"""
        req_file = Path.cwd() / "requirements.txt"
        if req_file.exists():
            return req_file.read_text(encoding="utf-8")
        return "No requirements.txt found"

    def get_setup_info(self) -> str:
        """Get setup.py or pyproject.toml content"""
        setup_file = Path.cwd() / "setup.py"
        if setup_file.exists():
            return setup_file.read_text(encoding="utf-8")

        pyproject_file = Path.cwd() / "pyproject.toml"
        if pyproject_file.exists():
            return pyproject_file.read_text(encoding="utf-8")

        return "No setup.py or pyproject.toml found"

    def format_endpoints_for_prompt(self, endpoints: List[Dict[str, Any]]) -> str:
        """Format endpoints for AI prompt"""
        formatted = []
        for endpoint in endpoints:
            formatted.append(
                f"""
            File: {endpoint['file']}
            Method: {endpoint['method']}
            Path: {endpoint['path']}
            Code: {endpoint['code']}
            """
            )
        return "\n".join(formatted)

    def update_main_readme(self):
        """Update the main README.md file"""
        readme_file = self.output_dir / "README.md"
        prompt = f"""
        Generate a comprehensive README for this Python project:
        Project: {self.project_config.get('projectName', 'Unknown')}
        Please provide:
        1. Project overview
        2. Features
        3. Installation instructions
        4. Usage examples
        5. Contribution guidelines
        6. License information
        Format as Markdown.
        """

        response = openai.chat.completions.create(
            model=self.deployment_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=self.temperature,
            max_tokens=self.max_tokens,
        )

        readme_content = response.choices[0].message.content

        with open(readme_file, "w", encoding="utf-8") as f:
            f.write(f"# README\n\n{readme_content}\n\n---\n*Generated by CopilotFlow AI*")

    def generate_index(self, results: Dict[str, Any]):
        """Generate documentation index"""
        index_file = self.output_dir / "ARCHITECTURE.md"
        prompt = f"""
        Generate a documentation index and architecture overview for this Python project:
        Project: {self.project_config.get('projectName', 'Unknown')}
        Documentation files: {json.dumps(results, indent=2)}
        Please provide:
        1. High-level architecture diagram (ASCII)
        2. Index of documentation files
        3. Brief description of each file
        Format as Markdown.
        """

        response = openai.chat.completions.create(
            model=self.deployment_name,
            messages=[{"role": "user", "content": prompt}],
            temperature=self.temperature,
            max_tokens=self.max_tokens,
        )

        index_content = response.choices[0].message.content

        with open(index_file, "w", encoding="utf-8") as f:
            f.write(f"# Architecture & Documentation Index\n\n{index_content}\n\n---\n*Generated by CopilotFlow AI*")


if __name__ == "__main__":
    generator = PythonDocumentationGenerator()
    generator.generate_docs()
