// Unit test for CopilotFlow MVE Enforcement Script
// Attribution: Generated by GitHub Copilot

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

describe('MVE Enforcement Script', () => {
  const docsDir = path.resolve('docs');
  const scriptPath = path.resolve('scripts/mve-enforce.js');

  beforeAll(() => {
    // Ensure docs directory exists
    if (!fs.existsSync(docsDir)) fs.mkdirSync(docsDir);
    // Create all required docs with all required sections
    const sections = [
      'Experiment Framing',
      'Hypothesis',
      'Impact & Success Metrics',
      'Dependencies & Readiness',
      'Experiment Design & Planning',
      'Execution & Iteration',
      'Results & Review',
      'References & Citations',
    ];
    for (const doc of [
      'PROJECT_CONTEXT.md',
      'EXPERIMENT_LOG.md',
      'RESULTS_REVIEW.md',
      'REFERENCES.md',
    ]) {
      fs.writeFileSync(path.join(docsDir, doc), sections.join('\n'));
    }
  });

  afterAll(() => {
    // Clean up created docs
    for (const doc of [
      'PROJECT_CONTEXT.md',
      'EXPERIMENT_LOG.md',
      'RESULTS_REVIEW.md',
      'REFERENCES.md',
    ]) {
      fs.unlinkSync(path.join(docsDir, doc));
    }
  });

  it('should pass when all docs and sections are present', () => {
    expect(() => execSync(`node ${scriptPath}`)).not.toThrow();
  });

  it('should fail if a required doc is missing', () => {
    fs.unlinkSync(path.join(docsDir, 'PROJECT_CONTEXT.md'));
    expect(() => execSync(`node ${scriptPath}`)).toThrow();
    // Restore
    fs.writeFileSync(
      path.join(docsDir, 'PROJECT_CONTEXT.md'),
      requiredSections.join('\n')
    );
  });

  it('should fail if a required section is missing', () => {
    fs.writeFileSync(
      path.join(docsDir, 'EXPERIMENT_LOG.md'),
      'Experiment Framing'
    );
    expect(() => execSync(`node ${scriptPath}`)).toThrow();
    // Restore
    fs.writeFileSync(
      path.join(docsDir, 'EXPERIMENT_LOG.md'),
      requiredSections.join('\n')
    );
  });
});

const requiredSections = [
  'Experiment Framing',
  'Hypothesis',
  'Impact & Success Metrics',
  'Dependencies & Readiness',
  'Experiment Design & Planning',
  'Execution & Iteration',
  'Results & Review',
  'References & Citations',
];
