// CopilotFlow MVE Enforcement Script
// Enforces Minimum Viable Experiment documentation and workflow compliance.
// Attribution: Generated by GitHub Copilot

const fs = require('fs');
const path = require('path');

const requiredDocs = [
  'docs/PROJECT_CONTEXT.md',
  'docs/EXPERIMENT_LOG.md',
  'docs/RESULTS_REVIEW.md',
  'docs/REFERENCES.md',
];

const requiredSections = [
  'Experiment Framing',
  'Hypothesis',
  'Impact & Success Metrics',
  'Dependencies & Readiness',
  'Experiment Design & Planning',
  'Execution & Iteration',
  'Results & Review',
  'References & Citations',
];

function createDocIfMissing(docPath) {
  if (!fs.existsSync(docPath)) {
    fs.writeFileSync(
      docPath,
      `# ${path.basename(docPath)}\n\nThis file is auto-generated to comply with MVE documentation standards.\n\n${requiredSections
        .map(s => `## ${s}\n\n*Add content here.*\n`)
        .join('\n')}`
    );
    console.log(`🛠️ Created missing documentation file: ${docPath}`);
  }
}

function checkDocs() {
  const missingDocs = [];
  for (const doc of requiredDocs) {
    const docPath = path.resolve(doc);
    if (!fs.existsSync(docPath)) {
      missingDocs.push(doc);
      createDocIfMissing(docPath);
    }
  }
  return missingDocs;
}

function insertSectionIfMissing(docPath, section) {
  let content = fs.readFileSync(docPath, 'utf-8');
  if (!content.includes(section)) {
    content += `\n## ${section}\n\n*Add content here.*\n`;
    fs.writeFileSync(docPath, content);
    console.log(`🛠️ Inserted missing section '${section}' into ${docPath}`);
  }
}

function checkSections(docPath, sections) {
  if (!fs.existsSync(docPath)) return [];
  const content = fs.readFileSync(docPath, 'utf-8');
  const missing = sections.filter(section => !content.includes(section));
  missing.forEach(section => insertSectionIfMissing(docPath, section));
  return missing;
}

function main() {
  console.log('🔎 CopilotFlow MVE Compliance & Auto-Repair');
  const missingDocs = checkDocs();
  if (missingDocs.length > 0) {
    console.error(
      '❌ Missing documentation files detected:',
      missingDocs.join(', ')
    );
    // Auto-create but signal failure for CI (tests expect throw/exit)
    console.error('Auto-created missing docs, please review and re-run.');
    process.exitCode = 1;
  }

  const incompleteSections = {};
  for (const doc of requiredDocs) {
    const docPath = path.resolve(doc);
    const missingSections = checkSections(docPath, requiredSections);
    if (missingSections.length > 0) {
      incompleteSections[doc] = missingSections;
    }
  }

  if (Object.keys(incompleteSections).length > 0) {
    for (const [doc, sections] of Object.entries(incompleteSections)) {
      console.error(`❌ ${doc} missing sections: ${sections.join(', ')}`);
    }
    console.error(
      'Auto-inserted missing sections. Please validate content before proceeding.'
    );
    process.exitCode = 1;
  }

  if (process.exitCode === 1) {
    // Provide a summary line for CI logs
    console.error(
      'MVE enforcement completed with repairs; manual review required.'
    );
  } else {
    console.log(
      '✅ All MVE documentation and sections are present. Proceeding with workflow.'
    );
  }
}

main();
